on: [push, pull_request]

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  msvc:
    name: MSVC
    strategy:
      fail-fast: false
      matrix:
        rust_version: [stable, 1.64.0]
        target:
          - x86_64-pc-windows-msvc
          - x86-pc-windows-msvc
          - aarch64-pc-windows-msvc

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version }}
          targets: ${{ matrix.target }}

      - run: cargo build --verbose --release --target ${{ matrix.target }}
      - if: contains(matrix.target, 'x86')
        run: cargo test --verbose --release
      - if: contains(matrix.target, 'x86')
        run: cargo run --verbose --release -- empty-resource.rc
      - run: cd example/version/; cargo build --target ${{ matrix.target }}